apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: easyspringpetclinic
  description: The spring-petclinic API
  tags:
    - failing
    - owner
    - pet
    - vet
    - visit
  links:
    - url: http://spring-petclinic.cnr.tap.tanzu.vxlab.local
      title: GitHub Repo
      icon: github
spec:
  type: openapi
  lifecycle: experimental
  owner: teamacic
  definition: |
    openapi: 3.0.1
    info:
      title: Spring PetClinic
      description: Spring PetClinic Sample Application.
      license:
        name: Apache 2.0
        url: http://www.apache.org/licenses/LICENSE-2.0
      version: '1.0'
    servers:
    - url: http://spring-petclinic.cnr.tap.tanzu.vxlab.local
    tags:
    - name: failing
      description: Endpoint which always returns an error.
    - name: owner
      description: Endpoints related to pet owners.
    - name: pet
      description: Endpoints related to pets.
    - name: vet
      description: Endpoints related to vets.
    - name: visit
      description: Endpoints related to vet visits.
    paths:
      /owners:
        get:
          tags:
          - owner
          operationId: listOwners
          summary: Lists pet owners
          description: Returns an array of pet owners.
          parameters:
          - name: lastName
            in: query
            description: Last name.
            required: false
            schema:
              type: string
              example: Davis
          responses:
            200:
              description: Owner details found and returned.
              headers:
                ETag:
                  description: An ID for this version of the response.
                  schema:
                    type: string
              content:
                text/html:
                  schema:
                    type: string
                  examples:
                    html:
                      summary: A list containing two items
                      value: '<html><body><ul><li>firstName</li><li>lastName</li></ul></body></html>'
                application/xml:
                  schema:
                    $ref: '#/components/schemas/OwnerFields'
                application/json:
                  schema:
                    $ref: '#/components/schemas/OwnerFields'
    components:
      schemas:
        OwnerFields:
          title: Owner fields
          description: Editable fields of a pet owner.
          type: object
          properties:
            firstName:
              title: First name
              description: The first name of the pet owner.
              type: string
              minLength: 1
              maxLength: 30
              pattern: '^[a-zA-Z]*$'
              example: George
            lastName:
              title: Last name
              description: The last name of the pet owner.
              type: string
              minLength: 1
              maxLength: 30
              pattern: '^[a-zA-Z]*$'
              example: Franklin
            address:
              title: Address
              description: The postal address of the pet owner.
              type: string
              minLength: 1
              maxLength: 255
              example: '110 W. Liberty St.'
            city:
              title: City
              description: The city of the pet owner.
              type: string
              minLength: 1
              maxLength: 80
              example: Madison
            telephone:
              title: Telephone number
              description: The telephone number of the pet owner.
              type: string
              minLength: 1
              maxLength: 20
              pattern: '^[0-9]*$'
              example: '6085551023'
          required:
            - firstName
            - lastName
            - address
            - city
            - telephone
